"""empty message

Revision ID: 2f19e35f4b05
Revises: 43d4fb49f772
Create Date: 2022-05-19 18:18:36.538557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f19e35f4b05'
down_revision = '43d4fb49f772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'token')
    # ### end Alembic commands ###