"""empty message

Revision ID: 4153d49ccdd5
Revises: 6c90d40d9966
Create Date: 2022-04-15 06:56:37.447005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4153d49ccdd5'
down_revision = '6c90d40d9966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('hint', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'hint')
    # ### end Alembic commands ###