"""empty message

Revision ID: 467a40844818
Revises: 2fab75990517
Create Date: 2022-04-15 07:31:38.616469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467a40844818'
down_revision = '2fab75990517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'password',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('student', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'password',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###