"""empty message

Revision ID: 5e5d758468bf
Revises: 43d4fb49f772
Create Date: 2022-05-19 18:19:59.263576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5d758468bf'
down_revision = '43d4fb49f772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'token')
    # ### end Alembic commands ###