"""empty message

Revision ID: 9af60606f216
Revises: 4153d49ccdd5
Create Date: 2022-04-15 07:25:25.304076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af60606f216'
down_revision = '4153d49ccdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'user_name')
    # ### end Alembic commands ###