"""empty message

Revision ID: 1b0b5b9acbac
Revises: 32e30ea2879e
Create Date: 2022-05-19 22:59:14.612694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0b5b9acbac'
down_revision = '32e30ea2879e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answerA', sa.String(length=120), nullable=True))
    op.add_column('question', sa.Column('answerB', sa.String(length=120), nullable=True))
    op.add_column('question', sa.Column('answerC', sa.String(length=120), nullable=True))
    op.add_column('question', sa.Column('answerD', sa.String(length=120), nullable=True))
    op.add_column('question', sa.Column('answerCorrect', sa.String(length=120), nullable=True))
    op.drop_column('question', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('question', 'answerCorrect')
    op.drop_column('question', 'answerD')
    op.drop_column('question', 'answerC')
    op.drop_column('question', 'answerB')
    op.drop_column('question', 'answerA')
    # ### end Alembic commands ###