"""empty message

Revision ID: 3398c9888c76
Revises: 1b0b5b9acbac
Create Date: 2022-05-20 20:56:12.284148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3398c9888c76'
down_revision = '1b0b5b9acbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('user_score', sa.Integer(), nullable=True))
    op.drop_column('score', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('score', 'user_score')
    # ### end Alembic commands ###